### ISSUE TITLE
Missing parts

### ISSUE THREAD

**Issue by Ultimaboot** [jbrazio/arduheater#1]
Hello,

I can not find the following parts:

**PCB vs BOM:**
C 10pF not found on PCB, is this the component between nano and DHT22?
C 4,7uF not found on PCB, is this the component between nano and DHT22?
ESP32 not found on PCB.
SPX1117 or IRF3205 used?
AM2320 or DHT22 used?
What are the TX, RX and GND for?
On the backside of the box there is a opening for the USB, the other one is for the power i asuming. What connector is used?

**3D print:**
I only have the box file but not the top of the box.

With Regards,

Peter Boot

**Comment by jbrazio** [comment]
Hi @Ultimaboot, I was out for the last week.
The [Thingiverse page](https://www.thingiverse.com/thing:2614341) has been updated with all the required STL files. I've also update the [BOM list](https://github.com/jbrazio/arduheater/blob/master/README.md#bom) with the correct part numbers and values.

The MOSFET in use is the IRF3205.
Nevermind the ESP32, SPX1117 parts.
The AM2320 and the DHT22 are interchangable.
The TX, RX and GND are just a test pads which break out the Arduino serial.

The power cable is directly attached to the `J1` connector which is a screw terminal.

**Comment by jbrazio** [comment]
The AM2320 and the DHT22 are interchangable.

**Comment by Ultimaboot** [comment]
Hey thanks for the update.
I Thought you were on vacation, no problem. Everyone has the right to
vacation.

Op ma 17 jun. 2019 om 11:18 schreef João Brázio <notifications@github.com>:

**Comment by Ultimaboot** [comment]
Hey thanks for the update.
I Thought you were on vacation, no problem. Everyone has the right to vacation.
