### ISSUE TITLE
inline fuse on the 12V feed line

### ISSUE THREAD

**Issue by Ultimaboot** [jbrazio/arduheater#2]
Hello,
question about inline fuse on the 12V feed line.
How big should the fuse be? And what part do you recommend for a the PTC Resetable Fuse?

Thanks, your doing a great job.

With Regards

Peter Boot

**Comment by jbrazio** [comment]
Hi Peter,

It depends on the true load of each heating strip, but considering 1A max per channel using 4 channels, a 4A inline fuse should be enough. I believe the fuss around the PTC would not worth the effort, usually all 12V astronomy equipment is protected by a standard blow-type fuse.

**Comment by Ultimaboot** [comment]
Thanks for the reply.
Just waiting for some parts and than I'm gone to build the Arduheater.
How can i adjust the settings, is there a window program for. I saw some photo's 
Dew Controller V3.5,2???
Where can I find it?

**Comment by jbrazio** [comment]
Actually I do have a frontend application for Arduheater, [check it out here](https://github.com/jbrazio/arduheater-gui-win). You will need Visual Studio 2019 to compile it into a binary or you can download a [pre build version from here](https://cld.pt/dl/download/aabb8fdf-5333-4c93-b34f-9bbf01024b24/0.2019.3.7.zip).
